services:
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=4002
    ports:
      - "4002:4002"
    networks:
      - chat-bot
  
  chat-bot-mongo:
    container_name: chat-bot-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Kalarkson
      MONGO_INITDB_ROOT_PASSWORD: qwerty-chat-bot
    ports:
      - "27019:27017"
    networks:
      - chat-bot

networks:
  chat-bot: